const DEFAULT_ERROR = 500;

const NOT_FOUND_ERROR = 404;

const UNAUTHORIZED_ERROR = 401;

const FORBIDDEN_ERROR = 403;

const INVALID_DATA_ERROR = 400;

const CONFLICT_ERROR = 409;

module.exports = {
  DEFAULT_ERROR,
  NOT_FOUND_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  INVALID_DATA_ERROR,
  CONFLICT_ERROR,
};
